### ISSUE TITLE
Final Project Feedback

### ISSUE THREAD

**Issue by aespaldi** [will0101/Graph_Caper#3]
Final Project Feedback

Overall 17/ 33 (> 20 Passing):  Not quite passing, this doesn't seem like your best work, but it is an interesting approach.  

- Proposal 1/4
- Code Graph Data structure 3/4
- Code: Solution 1:  3/4
- Code: Solution 2:  3/4
- Code: Solution 3: 3/4
- Code Documentation 3/4
- Code Testing 0/4
- Blog / Presentation 3/5
  -   Did not fully define the problem or the solutions you were solving, did not define the algorithms for the solutions.

**Comment by will0101** [comment]
I have questions about the grade of: 1/4: of my proposal and 0/4 for code testing
